default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
 adapter: postgresql
 database: doug_test_app
 encoding: unicode
 reaping_frequency: 3
 reconnect: true
 pool: 400
 timeout: 50000
